# Generated by Django 4.0.2 on 2022-02-17 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pcp',
            field=models.CharField(max_length=30, verbose_name='PCP'),
        ),
        migrations.CreateModel(
            name='User_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(choices=[(1, 'Patient'), (2, 'Nurse'), (3, 'Doctor'), (4, 'Admin'), (5, 'Family Member')])),
                ('deleted_bool', models.BooleanField()),
                ('time_modified', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_medications', models.CharField(max_length=30)),
                ('family_med_history', models.CharField(max_length=60, verbose_name='Family Medical History')),
                ('past_meds', models.CharField(max_length=60, verbose_name='Past Medications')),
                ('allergies', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('pulse', models.IntegerField()),
                ('blood_oxygen', models.CharField(max_length=4)),
                ('weight', models.IntegerField()),
                ('height', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('date_of_purchase', models.DateField()),
                ('MAC_address', models.CharField(max_length=30, verbose_name='MAC Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(max_length=30)),
                ('member_id', models.CharField(max_length=30)),
                ('member_name', models.CharField(max_length=60)),
                ('credit_card_number', models.CharField(max_length=16)),
                ('credit_card_expiration', models.CharField(max_length=5, verbose_name='Expiration date')),
                ('credit_card_cvv', models.CharField(max_length=3, verbose_name='CVV')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
    ]
